# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIfsRRNECO7Gt3NSYskZSyaWMLlLEt7k
"""

from google.colab import files
data=files.upload()

import pandas as pd

df = pd.read_csv("NFLX.csv")

df

pip install pandas matplotlib yfinance

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Define the stock symbol and time period
stock_symbol = 'AAPL'
start_date = '2021-01-01'
end_date = '2022-01-01'

# Download historical stock data
stock_data = yf.download(stock_symbol, start=start_date, end=end_date)

# Print the first few rows of the data
print(stock_data.head())

# Plot the stock closing prices
plt.figure(figsize=(10, 6))
plt.plot(stock_data['Close'], label=f'{stock_symbol} Stock Price')
plt.title(f'{stock_symbol} Stock Price Analysis')
plt.xlabel('Date')
plt.ylabel('Stock Price (USD)')
plt.legend()
plt.show()